In [ ]:
import torch
from torch import nn 

In [2]:
net = nn.Sequential(
    nn.LazyLinear(8),
    nn.ReLU(),
    nn.LazyLinear(1)
)

X = torch.rand(size=(2,4))
net(X).shape

torch.Size([2, 1])

In [6]:
#You can access a layer of a model by indexing into the model. You can access the parameters using the indexed layer

#Below code accesses the second linear layer
net[2].state_dict()

OrderedDict([('weight',
              tensor([[ 0.1150, -0.0530,  0.0074, -0.1925,  0.2213, -0.2876, -0.3219, -0.2877]])),
             ('bias', tensor([0.0795]))])

In [ ]:
#Each parameter in pytorch is an instance of Parameter class. Individual values can be accessed using .data attribute
net[2].bias.data

tensor([0.0795])

In [8]:
#Parameters also contain gradients. The gradient of a parameter can be accessed as follows
net[2].bias.grad

In [9]:
#Parameters of all layers can be accessed as follows
[(name, params.shape) for name, params in net.named_parameters()]

[('0.weight', torch.Size([8, 4])),
 ('0.bias', torch.Size([8])),
 ('2.weight', torch.Size([1, 8])),
 ('2.bias', torch.Size([1]))]

In [12]:
#You can tie/share model parameters across multiple layers
shared = nn.LazyLinear(8)
net = nn.Sequential(
    nn.LazyLinear(8), nn.ReLU(),
    shared, nn.ReLU(),
    shared, nn.ReLU(),
    nn.LazyLinear(1)
)
net(X)

print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([True, True, True, True, True, True, True, True])
