In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

In [7]:
#Here we build a layer with no parameters. This layer just centers the data along its mean
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [9]:
layer = CenteredLayer()
layer(torch.tensor([[1.0, 2, 3], [4, 5, 6]]))

tensor([[-2.5000, -1.5000, -0.5000],
        [ 0.5000,  1.5000,  2.5000]])

In [ ]:
#Now we create a custom layer with parameters.
class MyLinear(nn.Module): 
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [11]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 1.6406, -0.9399,  0.4064],
        [ 0.4027,  0.4946, -0.3283],
        [ 0.1970, -0.1728, -0.3179],
        [-1.3685, -0.7280,  0.3592],
        [ 0.0829,  1.0036, -1.2699]], requires_grad=True)

In [12]:
linear(torch.rand(2,5))

tensor([[0.2714, 0.7587, 0.0000],
        [0.0000, 0.8640, 0.0000]])