In [2]:
import torch

In [2]:
#Scalars and their common operations
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
#Vectors are tensors with one dimension
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
#Elements of a vector can be accessed by indexing
x[0], x[3], x[-1]

(tensor(0), tensor(3), tensor(3))

In [ ]:
#The dimensionality of a vector can be accessed by using length or its shape
print(len(x))
print(x.shape) #Shape returns a torch. For a vector, this torch has one element.

4
torch.Size([4])


In [8]:
#Matrices are tensors with two dimensions
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [10]:
#Transpose of a matric is obtained by swapping its axes
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [12]:
#A symmetric matrix is equal to its transpose
A = torch.tensor([[0.0, 1.0], [1.0, 0.0]])
A == A.T

tensor([[True, True],
        [True, True]])

In [13]:
#Tensors can have more than two dimensions. # The number of dimensions is called the rank of the tensor. 
# The shape of a tensor is a tuple of integers giving the size of the tensor along each dimension.
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [7]:
#Tensor arithmetric operations apply elementwise
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [17]:
#Element wise product of two tensors is called the Hadamard product
A * B

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])

In [18]:
#Operations between and tensor and scalar apply the operation to each element of the tensor
A, A + 2, A / 2, A**2

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[2, 3, 4],
         [5, 6, 7]]),
 tensor([[0.0000, 0.5000, 1.0000],
         [1.5000, 2.0000, 2.5000]]),
 tensor([[ 0,  1,  4],
         [ 9, 16, 25]]))

In [19]:
#Reduction - reduces tensors to scalars. For example, summing all the elements of a tensor reduces it to a scalar.
A, A.sum()

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor(15))

In [20]:
#To reduce along a particular axis, we can specify the axis argument. 
# For example, to sum along the rows (axis 0), we can do the following: 
A, A.sum(axis=0)

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([3, 5, 7]))

In [4]:
#To reduce along columns (axis 1), we can do the following:
A, A.sum(axis=1)

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([ 3, 12]))

In [10]:
#Mean can ve used to find the average of all elements in a tensor.
A, A.mean(), A.mean(axis=0), A.mean(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor(2.5000),
 tensor([1.5000, 2.5000, 3.5000]),
 tensor([1., 4.]))

In [11]:
#Non reduction sum keeps the dimensions of the original tensor by setting the keepdims argument to True.
A, A.sum(axis=0, keepdims=True), A.sum(axis=1, keepdims=True)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[3., 5., 7.]]),
 tensor([[ 3.],
         [12.]]))

In [13]:
#Dot product of two vectors is the sum of the products of their elements. It will be a scalar.
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32) * 2
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([2., 2., 2., 2.]), tensor(12.))

In [16]:
# Dot product between two matrices is the sum of the products of their elements along the last axis of the first matrix and the second to last axis of the second matrix. 
# It will be a matrix.
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = torch.ones(6).reshape(3, 2)
A, B, A@B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[ 3.,  3.],
         [12., 12.]]))

In [17]:
#Norm is a function that takes a vector as input and outputs a scalar. It is used to measure the magnitude of a vector.
u = torch.tensor([3.0, 4.0])
torch.norm(u) #l2 norm

tensor(5.)

In [18]:
#l1 norm is the sum of the absolute values of the elements of a vector. It is also called the Manhattan norm.
torch.norm(u, p=1)

tensor(7.)

In [19]:
#L2 norm of a matrix is called the Frobenius norm. It is the square root of the sum of the squares of the elements of the matrix.
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
torch.norm(A)

tensor(7.4162)